title: Finchers
description: Yet another Finch-inspired Web framework for Rust
url: ""
baseurl: ""

theme: minima

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: rust
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

plugins:
  - jekyll-feed
